run:
  concurrency: 2
  timeout: 5m
  skip-dirs:
    - appstoreconnect

linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/micnncim/appstoreconnect-go)
      - blank
      - dot
