/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the EndAppAvailabilityPreOrderCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndAppAvailabilityPreOrderCreateRequestDataRelationships{}

// EndAppAvailabilityPreOrderCreateRequestDataRelationships struct for EndAppAvailabilityPreOrderCreateRequestDataRelationships
type EndAppAvailabilityPreOrderCreateRequestDataRelationships struct {
	TerritoryAvailabilities AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities `json:"territoryAvailabilities"`
}

// NewEndAppAvailabilityPreOrderCreateRequestDataRelationships instantiates a new EndAppAvailabilityPreOrderCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndAppAvailabilityPreOrderCreateRequestDataRelationships(territoryAvailabilities AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) *EndAppAvailabilityPreOrderCreateRequestDataRelationships {
	this := EndAppAvailabilityPreOrderCreateRequestDataRelationships{}
	this.TerritoryAvailabilities = territoryAvailabilities
	return &this
}

// NewEndAppAvailabilityPreOrderCreateRequestDataRelationshipsWithDefaults instantiates a new EndAppAvailabilityPreOrderCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndAppAvailabilityPreOrderCreateRequestDataRelationshipsWithDefaults() *EndAppAvailabilityPreOrderCreateRequestDataRelationships {
	this := EndAppAvailabilityPreOrderCreateRequestDataRelationships{}
	return &this
}

// GetTerritoryAvailabilities returns the TerritoryAvailabilities field value
func (o *EndAppAvailabilityPreOrderCreateRequestDataRelationships) GetTerritoryAvailabilities() AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities {
	if o == nil {
		var ret AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
		return ret
	}

	return o.TerritoryAvailabilities
}

// GetTerritoryAvailabilitiesOk returns a tuple with the TerritoryAvailabilities field value
// and a boolean to check if the value has been set.
func (o *EndAppAvailabilityPreOrderCreateRequestDataRelationships) GetTerritoryAvailabilitiesOk() (*AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TerritoryAvailabilities, true
}

// SetTerritoryAvailabilities sets field value
func (o *EndAppAvailabilityPreOrderCreateRequestDataRelationships) SetTerritoryAvailabilities(v AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) {
	o.TerritoryAvailabilities = v
}

func (o EndAppAvailabilityPreOrderCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndAppAvailabilityPreOrderCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["territoryAvailabilities"] = o.TerritoryAvailabilities
	return toSerialize, nil
}

type NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships struct {
	value *EndAppAvailabilityPreOrderCreateRequestDataRelationships
	isSet bool
}

func (v NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) Get() *EndAppAvailabilityPreOrderCreateRequestDataRelationships {
	return v.value
}

func (v *NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) Set(val *EndAppAvailabilityPreOrderCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndAppAvailabilityPreOrderCreateRequestDataRelationships(val *EndAppAvailabilityPreOrderCreateRequestDataRelationships) *NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships {
	return &NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndAppAvailabilityPreOrderCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
