/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAppVersionCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAppVersionCreateRequestData{}

// GameCenterAppVersionCreateRequestData struct for GameCenterAppVersionCreateRequestData
type GameCenterAppVersionCreateRequestData struct {
	Type          string                                             `json:"type"`
	Relationships AppStoreReviewDetailCreateRequestDataRelationships `json:"relationships"`
}

// NewGameCenterAppVersionCreateRequestData instantiates a new GameCenterAppVersionCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAppVersionCreateRequestData(type_ string, relationships AppStoreReviewDetailCreateRequestDataRelationships) *GameCenterAppVersionCreateRequestData {
	this := GameCenterAppVersionCreateRequestData{}
	this.Type = type_
	this.Relationships = relationships
	return &this
}

// NewGameCenterAppVersionCreateRequestDataWithDefaults instantiates a new GameCenterAppVersionCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAppVersionCreateRequestDataWithDefaults() *GameCenterAppVersionCreateRequestData {
	this := GameCenterAppVersionCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterAppVersionCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterAppVersionCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterAppVersionCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetRelationships returns the Relationships field value
func (o *GameCenterAppVersionCreateRequestData) GetRelationships() AppStoreReviewDetailCreateRequestDataRelationships {
	if o == nil {
		var ret AppStoreReviewDetailCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *GameCenterAppVersionCreateRequestData) GetRelationshipsOk() (*AppStoreReviewDetailCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *GameCenterAppVersionCreateRequestData) SetRelationships(v AppStoreReviewDetailCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o GameCenterAppVersionCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAppVersionCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

type NullableGameCenterAppVersionCreateRequestData struct {
	value *GameCenterAppVersionCreateRequestData
	isSet bool
}

func (v NullableGameCenterAppVersionCreateRequestData) Get() *GameCenterAppVersionCreateRequestData {
	return v.value
}

func (v *NullableGameCenterAppVersionCreateRequestData) Set(val *GameCenterAppVersionCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAppVersionCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAppVersionCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAppVersionCreateRequestData(val *GameCenterAppVersionCreateRequestData) *NullableGameCenterAppVersionCreateRequestData {
	return &NullableGameCenterAppVersionCreateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterAppVersionCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAppVersionCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
