/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the AppRelationshipsGameCenterDetailData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppRelationshipsGameCenterDetailData{}

// AppRelationshipsGameCenterDetailData struct for AppRelationshipsGameCenterDetailData
type AppRelationshipsGameCenterDetailData struct {
	Type string `json:"type"`
	Id   string `json:"id"`
}

// NewAppRelationshipsGameCenterDetailData instantiates a new AppRelationshipsGameCenterDetailData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppRelationshipsGameCenterDetailData(type_ string, id string) *AppRelationshipsGameCenterDetailData {
	this := AppRelationshipsGameCenterDetailData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewAppRelationshipsGameCenterDetailDataWithDefaults instantiates a new AppRelationshipsGameCenterDetailData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppRelationshipsGameCenterDetailDataWithDefaults() *AppRelationshipsGameCenterDetailData {
	this := AppRelationshipsGameCenterDetailData{}
	return &this
}

// GetType returns the Type field value
func (o *AppRelationshipsGameCenterDetailData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppRelationshipsGameCenterDetailData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppRelationshipsGameCenterDetailData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *AppRelationshipsGameCenterDetailData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppRelationshipsGameCenterDetailData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppRelationshipsGameCenterDetailData) SetId(v string) {
	o.Id = v
}

func (o AppRelationshipsGameCenterDetailData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppRelationshipsGameCenterDetailData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableAppRelationshipsGameCenterDetailData struct {
	value *AppRelationshipsGameCenterDetailData
	isSet bool
}

func (v NullableAppRelationshipsGameCenterDetailData) Get() *AppRelationshipsGameCenterDetailData {
	return v.value
}

func (v *NullableAppRelationshipsGameCenterDetailData) Set(val *AppRelationshipsGameCenterDetailData) {
	v.value = val
	v.isSet = true
}

func (v NullableAppRelationshipsGameCenterDetailData) IsSet() bool {
	return v.isSet
}

func (v *NullableAppRelationshipsGameCenterDetailData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppRelationshipsGameCenterDetailData(val *AppRelationshipsGameCenterDetailData) *NullableAppRelationshipsGameCenterDetailData {
	return &NullableAppRelationshipsGameCenterDetailData{value: val, isSet: true}
}

func (v NullableAppRelationshipsGameCenterDetailData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppRelationshipsGameCenterDetailData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
