/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardSetCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardSetCreateRequestData{}

// GameCenterLeaderboardSetCreateRequestData struct for GameCenterLeaderboardSetCreateRequestData
type GameCenterLeaderboardSetCreateRequestData struct {
	Type          string                                                 `json:"type"`
	Attributes    GameCenterLeaderboardSetCreateRequestDataAttributes    `json:"attributes"`
	Relationships GameCenterLeaderboardSetCreateRequestDataRelationships `json:"relationships"`
}

// NewGameCenterLeaderboardSetCreateRequestData instantiates a new GameCenterLeaderboardSetCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardSetCreateRequestData(type_ string, attributes GameCenterLeaderboardSetCreateRequestDataAttributes, relationships GameCenterLeaderboardSetCreateRequestDataRelationships) *GameCenterLeaderboardSetCreateRequestData {
	this := GameCenterLeaderboardSetCreateRequestData{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewGameCenterLeaderboardSetCreateRequestDataWithDefaults instantiates a new GameCenterLeaderboardSetCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardSetCreateRequestDataWithDefaults() *GameCenterLeaderboardSetCreateRequestData {
	this := GameCenterLeaderboardSetCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterLeaderboardSetCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterLeaderboardSetCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GameCenterLeaderboardSetCreateRequestData) GetAttributes() GameCenterLeaderboardSetCreateRequestDataAttributes {
	if o == nil {
		var ret GameCenterLeaderboardSetCreateRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetCreateRequestData) GetAttributesOk() (*GameCenterLeaderboardSetCreateRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GameCenterLeaderboardSetCreateRequestData) SetAttributes(v GameCenterLeaderboardSetCreateRequestDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *GameCenterLeaderboardSetCreateRequestData) GetRelationships() GameCenterLeaderboardSetCreateRequestDataRelationships {
	if o == nil {
		var ret GameCenterLeaderboardSetCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetCreateRequestData) GetRelationshipsOk() (*GameCenterLeaderboardSetCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *GameCenterLeaderboardSetCreateRequestData) SetRelationships(v GameCenterLeaderboardSetCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o GameCenterLeaderboardSetCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardSetCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

type NullableGameCenterLeaderboardSetCreateRequestData struct {
	value *GameCenterLeaderboardSetCreateRequestData
	isSet bool
}

func (v NullableGameCenterLeaderboardSetCreateRequestData) Get() *GameCenterLeaderboardSetCreateRequestData {
	return v.value
}

func (v *NullableGameCenterLeaderboardSetCreateRequestData) Set(val *GameCenterLeaderboardSetCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardSetCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardSetCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardSetCreateRequestData(val *GameCenterLeaderboardSetCreateRequestData) *NullableGameCenterLeaderboardSetCreateRequestData {
	return &NullableGameCenterLeaderboardSetCreateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardSetCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardSetCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
