/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardSetReleaseCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardSetReleaseCreateRequestDataRelationships{}

// GameCenterLeaderboardSetReleaseCreateRequestDataRelationships struct for GameCenterLeaderboardSetReleaseCreateRequestDataRelationships
type GameCenterLeaderboardSetReleaseCreateRequestDataRelationships struct {
	GameCenterDetail         GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail                 `json:"gameCenterDetail"`
	GameCenterLeaderboardSet GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet `json:"gameCenterLeaderboardSet"`
}

// NewGameCenterLeaderboardSetReleaseCreateRequestDataRelationships instantiates a new GameCenterLeaderboardSetReleaseCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardSetReleaseCreateRequestDataRelationships(gameCenterDetail GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail, gameCenterLeaderboardSet GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet) *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships {
	this := GameCenterLeaderboardSetReleaseCreateRequestDataRelationships{}
	this.GameCenterDetail = gameCenterDetail
	this.GameCenterLeaderboardSet = gameCenterLeaderboardSet
	return &this
}

// NewGameCenterLeaderboardSetReleaseCreateRequestDataRelationshipsWithDefaults instantiates a new GameCenterLeaderboardSetReleaseCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardSetReleaseCreateRequestDataRelationshipsWithDefaults() *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships {
	this := GameCenterLeaderboardSetReleaseCreateRequestDataRelationships{}
	return &this
}

// GetGameCenterDetail returns the GameCenterDetail field value
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) GetGameCenterDetail() GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail {
	if o == nil {
		var ret GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail
		return ret
	}

	return o.GameCenterDetail
}

// GetGameCenterDetailOk returns a tuple with the GameCenterDetail field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) GetGameCenterDetailOk() (*GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameCenterDetail, true
}

// SetGameCenterDetail sets field value
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) SetGameCenterDetail(v GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail) {
	o.GameCenterDetail = v
}

// GetGameCenterLeaderboardSet returns the GameCenterLeaderboardSet field value
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) GetGameCenterLeaderboardSet() GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet {
	if o == nil {
		var ret GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet
		return ret
	}

	return o.GameCenterLeaderboardSet
}

// GetGameCenterLeaderboardSetOk returns a tuple with the GameCenterLeaderboardSet field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) GetGameCenterLeaderboardSetOk() (*GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameCenterLeaderboardSet, true
}

// SetGameCenterLeaderboardSet sets field value
func (o *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) SetGameCenterLeaderboardSet(v GameCenterLeaderboardSetLocalizationCreateRequestDataRelationshipsGameCenterLeaderboardSet) {
	o.GameCenterLeaderboardSet = v
}

func (o GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gameCenterDetail"] = o.GameCenterDetail
	toSerialize["gameCenterLeaderboardSet"] = o.GameCenterLeaderboardSet
	return toSerialize, nil
}

type NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships struct {
	value *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships
	isSet bool
}

func (v NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) Get() *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships {
	return v.value
}

func (v *NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) Set(val *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships(val *GameCenterLeaderboardSetReleaseCreateRequestDataRelationships) *NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships {
	return &NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardSetReleaseCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
