/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities{}

// AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities struct for AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
type AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities struct {
	Data []AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner `json:"data"`
}

// NewAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities instantiates a new AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities(data []AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner) *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities {
	this := AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities{}
	this.Data = data
	return &this
}

// NewAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesWithDefaults instantiates a new AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilitiesWithDefaults() *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities {
	this := AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities{}
	return &this
}

// GetData returns the Data field value
func (o *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) GetData() []AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner {
	if o == nil {
		var ret []AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) GetDataOk() ([]AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) SetData(v []AppAvailabilityV2RelationshipsTerritoryAvailabilitiesDataInner) {
	o.Data = v
}

func (o AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities struct {
	value *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities
	isSet bool
}

func (v NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) Get() *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities {
	return v.value
}

func (v *NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) Set(val *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities(val *AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) *NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities {
	return &NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities{value: val, isSet: true}
}

func (v NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
