/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the TerritoryAvailabilityUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerritoryAvailabilityUpdateRequest{}

// TerritoryAvailabilityUpdateRequest struct for TerritoryAvailabilityUpdateRequest
type TerritoryAvailabilityUpdateRequest struct {
	Data TerritoryAvailabilityUpdateRequestData `json:"data"`
}

// NewTerritoryAvailabilityUpdateRequest instantiates a new TerritoryAvailabilityUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerritoryAvailabilityUpdateRequest(data TerritoryAvailabilityUpdateRequestData) *TerritoryAvailabilityUpdateRequest {
	this := TerritoryAvailabilityUpdateRequest{}
	this.Data = data
	return &this
}

// NewTerritoryAvailabilityUpdateRequestWithDefaults instantiates a new TerritoryAvailabilityUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerritoryAvailabilityUpdateRequestWithDefaults() *TerritoryAvailabilityUpdateRequest {
	this := TerritoryAvailabilityUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *TerritoryAvailabilityUpdateRequest) GetData() TerritoryAvailabilityUpdateRequestData {
	if o == nil {
		var ret TerritoryAvailabilityUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TerritoryAvailabilityUpdateRequest) GetDataOk() (*TerritoryAvailabilityUpdateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TerritoryAvailabilityUpdateRequest) SetData(v TerritoryAvailabilityUpdateRequestData) {
	o.Data = v
}

func (o TerritoryAvailabilityUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerritoryAvailabilityUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableTerritoryAvailabilityUpdateRequest struct {
	value *TerritoryAvailabilityUpdateRequest
	isSet bool
}

func (v NullableTerritoryAvailabilityUpdateRequest) Get() *TerritoryAvailabilityUpdateRequest {
	return v.value
}

func (v *NullableTerritoryAvailabilityUpdateRequest) Set(val *TerritoryAvailabilityUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTerritoryAvailabilityUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTerritoryAvailabilityUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerritoryAvailabilityUpdateRequest(val *TerritoryAvailabilityUpdateRequest) *NullableTerritoryAvailabilityUpdateRequest {
	return &NullableTerritoryAvailabilityUpdateRequest{value: val, isSet: true}
}

func (v NullableTerritoryAvailabilityUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerritoryAvailabilityUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
