/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail{}

// GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail struct for GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail
type GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail struct {
	Data *AppRelationshipsGameCenterDetailData `json:"data,omitempty"`
}

// NewGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail instantiates a new GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail() *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail {
	this := GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail{}
	return &this
}

// NewGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetailWithDefaults instantiates a new GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetailWithDefaults() *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail {
	this := GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) GetData() AppRelationshipsGameCenterDetailData {
	if o == nil || IsNil(o.Data) {
		var ret AppRelationshipsGameCenterDetailData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) GetDataOk() (*AppRelationshipsGameCenterDetailData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AppRelationshipsGameCenterDetailData and assigns it to the Data field.
func (o *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) SetData(v AppRelationshipsGameCenterDetailData) {
	o.Data = &v
}

func (o GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail struct {
	value *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail
	isSet bool
}

func (v NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) Get() *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail {
	return v.value
}

func (v *NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) Set(val *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail(val *GameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) *NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail {
	return &NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail{value: val, isSet: true}
}

func (v NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAchievementCreateRequestDataRelationshipsGameCenterDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
