/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardSetImageCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardSetImageCreateRequestDataRelationships{}

// GameCenterLeaderboardSetImageCreateRequestDataRelationships struct for GameCenterLeaderboardSetImageCreateRequestDataRelationships
type GameCenterLeaderboardSetImageCreateRequestDataRelationships struct {
	GameCenterLeaderboardSetLocalization GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization `json:"gameCenterLeaderboardSetLocalization"`
}

// NewGameCenterLeaderboardSetImageCreateRequestDataRelationships instantiates a new GameCenterLeaderboardSetImageCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardSetImageCreateRequestDataRelationships(gameCenterLeaderboardSetLocalization GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization) *GameCenterLeaderboardSetImageCreateRequestDataRelationships {
	this := GameCenterLeaderboardSetImageCreateRequestDataRelationships{}
	this.GameCenterLeaderboardSetLocalization = gameCenterLeaderboardSetLocalization
	return &this
}

// NewGameCenterLeaderboardSetImageCreateRequestDataRelationshipsWithDefaults instantiates a new GameCenterLeaderboardSetImageCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardSetImageCreateRequestDataRelationshipsWithDefaults() *GameCenterLeaderboardSetImageCreateRequestDataRelationships {
	this := GameCenterLeaderboardSetImageCreateRequestDataRelationships{}
	return &this
}

// GetGameCenterLeaderboardSetLocalization returns the GameCenterLeaderboardSetLocalization field value
func (o *GameCenterLeaderboardSetImageCreateRequestDataRelationships) GetGameCenterLeaderboardSetLocalization() GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization {
	if o == nil {
		var ret GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization
		return ret
	}

	return o.GameCenterLeaderboardSetLocalization
}

// GetGameCenterLeaderboardSetLocalizationOk returns a tuple with the GameCenterLeaderboardSetLocalization field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetImageCreateRequestDataRelationships) GetGameCenterLeaderboardSetLocalizationOk() (*GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameCenterLeaderboardSetLocalization, true
}

// SetGameCenterLeaderboardSetLocalization sets field value
func (o *GameCenterLeaderboardSetImageCreateRequestDataRelationships) SetGameCenterLeaderboardSetLocalization(v GameCenterLeaderboardSetImageCreateRequestDataRelationshipsGameCenterLeaderboardSetLocalization) {
	o.GameCenterLeaderboardSetLocalization = v
}

func (o GameCenterLeaderboardSetImageCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardSetImageCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gameCenterLeaderboardSetLocalization"] = o.GameCenterLeaderboardSetLocalization
	return toSerialize, nil
}

type NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships struct {
	value *GameCenterLeaderboardSetImageCreateRequestDataRelationships
	isSet bool
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) Get() *GameCenterLeaderboardSetImageCreateRequestDataRelationships {
	return v.value
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) Set(val *GameCenterLeaderboardSetImageCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardSetImageCreateRequestDataRelationships(val *GameCenterLeaderboardSetImageCreateRequestDataRelationships) *NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships {
	return &NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
