/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAchievementCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAchievementCreateRequest{}

// GameCenterAchievementCreateRequest struct for GameCenterAchievementCreateRequest
type GameCenterAchievementCreateRequest struct {
	Data GameCenterAchievementCreateRequestData `json:"data"`
}

// NewGameCenterAchievementCreateRequest instantiates a new GameCenterAchievementCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAchievementCreateRequest(data GameCenterAchievementCreateRequestData) *GameCenterAchievementCreateRequest {
	this := GameCenterAchievementCreateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterAchievementCreateRequestWithDefaults instantiates a new GameCenterAchievementCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAchievementCreateRequestWithDefaults() *GameCenterAchievementCreateRequest {
	this := GameCenterAchievementCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterAchievementCreateRequest) GetData() GameCenterAchievementCreateRequestData {
	if o == nil {
		var ret GameCenterAchievementCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementCreateRequest) GetDataOk() (*GameCenterAchievementCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterAchievementCreateRequest) SetData(v GameCenterAchievementCreateRequestData) {
	o.Data = v
}

func (o GameCenterAchievementCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAchievementCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterAchievementCreateRequest struct {
	value *GameCenterAchievementCreateRequest
	isSet bool
}

func (v NullableGameCenterAchievementCreateRequest) Get() *GameCenterAchievementCreateRequest {
	return v.value
}

func (v *NullableGameCenterAchievementCreateRequest) Set(val *GameCenterAchievementCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAchievementCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAchievementCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAchievementCreateRequest(val *GameCenterAchievementCreateRequest) *NullableGameCenterAchievementCreateRequest {
	return &NullableGameCenterAchievementCreateRequest{value: val, isSet: true}
}

func (v NullableGameCenterAchievementCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAchievementCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
