/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the BundleIdCapabilitiesWithoutIncludesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleIdCapabilitiesWithoutIncludesResponse{}

// BundleIdCapabilitiesWithoutIncludesResponse struct for BundleIdCapabilitiesWithoutIncludesResponse
type BundleIdCapabilitiesWithoutIncludesResponse struct {
	Data  []BundleId         `json:"data"`
	Links PagedDocumentLinks `json:"links"`
	Meta  *PagingInformation `json:"meta,omitempty"`
}

// NewBundleIdCapabilitiesWithoutIncludesResponse instantiates a new BundleIdCapabilitiesWithoutIncludesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleIdCapabilitiesWithoutIncludesResponse(data []BundleId, links PagedDocumentLinks) *BundleIdCapabilitiesWithoutIncludesResponse {
	this := BundleIdCapabilitiesWithoutIncludesResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewBundleIdCapabilitiesWithoutIncludesResponseWithDefaults instantiates a new BundleIdCapabilitiesWithoutIncludesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleIdCapabilitiesWithoutIncludesResponseWithDefaults() *BundleIdCapabilitiesWithoutIncludesResponse {
	this := BundleIdCapabilitiesWithoutIncludesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetData() []BundleId {
	if o == nil {
		var ret []BundleId
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetDataOk() ([]BundleId, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BundleIdCapabilitiesWithoutIncludesResponse) SetData(v []BundleId) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetLinks() PagedDocumentLinks {
	if o == nil {
		var ret PagedDocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetLinksOk() (*PagedDocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BundleIdCapabilitiesWithoutIncludesResponse) SetLinks(v PagedDocumentLinks) {
	o.Links = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetMeta() PagingInformation {
	if o == nil || IsNil(o.Meta) {
		var ret PagingInformation
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) GetMetaOk() (*PagingInformation, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PagingInformation and assigns it to the Meta field.
func (o *BundleIdCapabilitiesWithoutIncludesResponse) SetMeta(v PagingInformation) {
	o.Meta = &v
}

func (o BundleIdCapabilitiesWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleIdCapabilitiesWithoutIncludesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBundleIdCapabilitiesWithoutIncludesResponse struct {
	value *BundleIdCapabilitiesWithoutIncludesResponse
	isSet bool
}

func (v NullableBundleIdCapabilitiesWithoutIncludesResponse) Get() *BundleIdCapabilitiesWithoutIncludesResponse {
	return v.value
}

func (v *NullableBundleIdCapabilitiesWithoutIncludesResponse) Set(val *BundleIdCapabilitiesWithoutIncludesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleIdCapabilitiesWithoutIncludesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleIdCapabilitiesWithoutIncludesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleIdCapabilitiesWithoutIncludesResponse(val *BundleIdCapabilitiesWithoutIncludesResponse) *NullableBundleIdCapabilitiesWithoutIncludesResponse {
	return &NullableBundleIdCapabilitiesWithoutIncludesResponse{value: val, isSet: true}
}

func (v NullableBundleIdCapabilitiesWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleIdCapabilitiesWithoutIncludesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
