/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardGroupLeaderboardLinkageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardGroupLeaderboardLinkageResponse{}

// GameCenterLeaderboardGroupLeaderboardLinkageResponse struct for GameCenterLeaderboardGroupLeaderboardLinkageResponse
type GameCenterLeaderboardGroupLeaderboardLinkageResponse struct {
	Data  GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner `json:"data"`
	Links DocumentLinks                                                `json:"links"`
}

// NewGameCenterLeaderboardGroupLeaderboardLinkageResponse instantiates a new GameCenterLeaderboardGroupLeaderboardLinkageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardGroupLeaderboardLinkageResponse(data GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner, links DocumentLinks) *GameCenterLeaderboardGroupLeaderboardLinkageResponse {
	this := GameCenterLeaderboardGroupLeaderboardLinkageResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewGameCenterLeaderboardGroupLeaderboardLinkageResponseWithDefaults instantiates a new GameCenterLeaderboardGroupLeaderboardLinkageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardGroupLeaderboardLinkageResponseWithDefaults() *GameCenterLeaderboardGroupLeaderboardLinkageResponse {
	this := GameCenterLeaderboardGroupLeaderboardLinkageResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) GetData() GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner {
	if o == nil {
		var ret GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) GetDataOk() (*GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) SetData(v GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) GetLinks() DocumentLinks {
	if o == nil {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GameCenterLeaderboardGroupLeaderboardLinkageResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o GameCenterLeaderboardGroupLeaderboardLinkageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardGroupLeaderboardLinkageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

type NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse struct {
	value *GameCenterLeaderboardGroupLeaderboardLinkageResponse
	isSet bool
}

func (v NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) Get() *GameCenterLeaderboardGroupLeaderboardLinkageResponse {
	return v.value
}

func (v *NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) Set(val *GameCenterLeaderboardGroupLeaderboardLinkageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardGroupLeaderboardLinkageResponse(val *GameCenterLeaderboardGroupLeaderboardLinkageResponse) *NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse {
	return &NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardGroupLeaderboardLinkageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
