/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the AppEncryptionDeclarationWithoutIncludesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppEncryptionDeclarationWithoutIncludesResponse{}

// AppEncryptionDeclarationWithoutIncludesResponse struct for AppEncryptionDeclarationWithoutIncludesResponse
type AppEncryptionDeclarationWithoutIncludesResponse struct {
	Data  Build         `json:"data"`
	Links DocumentLinks `json:"links"`
}

// NewAppEncryptionDeclarationWithoutIncludesResponse instantiates a new AppEncryptionDeclarationWithoutIncludesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppEncryptionDeclarationWithoutIncludesResponse(data Build, links DocumentLinks) *AppEncryptionDeclarationWithoutIncludesResponse {
	this := AppEncryptionDeclarationWithoutIncludesResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewAppEncryptionDeclarationWithoutIncludesResponseWithDefaults instantiates a new AppEncryptionDeclarationWithoutIncludesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppEncryptionDeclarationWithoutIncludesResponseWithDefaults() *AppEncryptionDeclarationWithoutIncludesResponse {
	this := AppEncryptionDeclarationWithoutIncludesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AppEncryptionDeclarationWithoutIncludesResponse) GetData() Build {
	if o == nil {
		var ret Build
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclarationWithoutIncludesResponse) GetDataOk() (*Build, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppEncryptionDeclarationWithoutIncludesResponse) SetData(v Build) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *AppEncryptionDeclarationWithoutIncludesResponse) GetLinks() DocumentLinks {
	if o == nil {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AppEncryptionDeclarationWithoutIncludesResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AppEncryptionDeclarationWithoutIncludesResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o AppEncryptionDeclarationWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppEncryptionDeclarationWithoutIncludesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

type NullableAppEncryptionDeclarationWithoutIncludesResponse struct {
	value *AppEncryptionDeclarationWithoutIncludesResponse
	isSet bool
}

func (v NullableAppEncryptionDeclarationWithoutIncludesResponse) Get() *AppEncryptionDeclarationWithoutIncludesResponse {
	return v.value
}

func (v *NullableAppEncryptionDeclarationWithoutIncludesResponse) Set(val *AppEncryptionDeclarationWithoutIncludesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppEncryptionDeclarationWithoutIncludesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppEncryptionDeclarationWithoutIncludesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppEncryptionDeclarationWithoutIncludesResponse(val *AppEncryptionDeclarationWithoutIncludesResponse) *NullableAppEncryptionDeclarationWithoutIncludesResponse {
	return &NullableAppEncryptionDeclarationWithoutIncludesResponse{value: val, isSet: true}
}

func (v NullableAppEncryptionDeclarationWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppEncryptionDeclarationWithoutIncludesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
