/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAchievementLocalizationCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAchievementLocalizationCreateRequestDataRelationships{}

// GameCenterAchievementLocalizationCreateRequestDataRelationships struct for GameCenterAchievementLocalizationCreateRequestDataRelationships
type GameCenterAchievementLocalizationCreateRequestDataRelationships struct {
	GameCenterAchievement GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement `json:"gameCenterAchievement"`
}

// NewGameCenterAchievementLocalizationCreateRequestDataRelationships instantiates a new GameCenterAchievementLocalizationCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAchievementLocalizationCreateRequestDataRelationships(gameCenterAchievement GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement) *GameCenterAchievementLocalizationCreateRequestDataRelationships {
	this := GameCenterAchievementLocalizationCreateRequestDataRelationships{}
	this.GameCenterAchievement = gameCenterAchievement
	return &this
}

// NewGameCenterAchievementLocalizationCreateRequestDataRelationshipsWithDefaults instantiates a new GameCenterAchievementLocalizationCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAchievementLocalizationCreateRequestDataRelationshipsWithDefaults() *GameCenterAchievementLocalizationCreateRequestDataRelationships {
	this := GameCenterAchievementLocalizationCreateRequestDataRelationships{}
	return &this
}

// GetGameCenterAchievement returns the GameCenterAchievement field value
func (o *GameCenterAchievementLocalizationCreateRequestDataRelationships) GetGameCenterAchievement() GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement {
	if o == nil {
		var ret GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement
		return ret
	}

	return o.GameCenterAchievement
}

// GetGameCenterAchievementOk returns a tuple with the GameCenterAchievement field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementLocalizationCreateRequestDataRelationships) GetGameCenterAchievementOk() (*GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameCenterAchievement, true
}

// SetGameCenterAchievement sets field value
func (o *GameCenterAchievementLocalizationCreateRequestDataRelationships) SetGameCenterAchievement(v GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement) {
	o.GameCenterAchievement = v
}

func (o GameCenterAchievementLocalizationCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAchievementLocalizationCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["gameCenterAchievement"] = o.GameCenterAchievement
	return toSerialize, nil
}

type NullableGameCenterAchievementLocalizationCreateRequestDataRelationships struct {
	value *GameCenterAchievementLocalizationCreateRequestDataRelationships
	isSet bool
}

func (v NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) Get() *GameCenterAchievementLocalizationCreateRequestDataRelationships {
	return v.value
}

func (v *NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) Set(val *GameCenterAchievementLocalizationCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAchievementLocalizationCreateRequestDataRelationships(val *GameCenterAchievementLocalizationCreateRequestDataRelationships) *NullableGameCenterAchievementLocalizationCreateRequestDataRelationships {
	return &NullableGameCenterAchievementLocalizationCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAchievementLocalizationCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
