/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the BuildsWithoutIncludesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildsWithoutIncludesResponse{}

// BuildsWithoutIncludesResponse struct for BuildsWithoutIncludesResponse
type BuildsWithoutIncludesResponse struct {
	Data  []PrereleaseVersion `json:"data"`
	Links PagedDocumentLinks  `json:"links"`
	Meta  *PagingInformation  `json:"meta,omitempty"`
}

// NewBuildsWithoutIncludesResponse instantiates a new BuildsWithoutIncludesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildsWithoutIncludesResponse(data []PrereleaseVersion, links PagedDocumentLinks) *BuildsWithoutIncludesResponse {
	this := BuildsWithoutIncludesResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewBuildsWithoutIncludesResponseWithDefaults instantiates a new BuildsWithoutIncludesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildsWithoutIncludesResponseWithDefaults() *BuildsWithoutIncludesResponse {
	this := BuildsWithoutIncludesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BuildsWithoutIncludesResponse) GetData() []PrereleaseVersion {
	if o == nil {
		var ret []PrereleaseVersion
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BuildsWithoutIncludesResponse) GetDataOk() ([]PrereleaseVersion, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BuildsWithoutIncludesResponse) SetData(v []PrereleaseVersion) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *BuildsWithoutIncludesResponse) GetLinks() PagedDocumentLinks {
	if o == nil {
		var ret PagedDocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *BuildsWithoutIncludesResponse) GetLinksOk() (*PagedDocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *BuildsWithoutIncludesResponse) SetLinks(v PagedDocumentLinks) {
	o.Links = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BuildsWithoutIncludesResponse) GetMeta() PagingInformation {
	if o == nil || IsNil(o.Meta) {
		var ret PagingInformation
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildsWithoutIncludesResponse) GetMetaOk() (*PagingInformation, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BuildsWithoutIncludesResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PagingInformation and assigns it to the Meta field.
func (o *BuildsWithoutIncludesResponse) SetMeta(v PagingInformation) {
	o.Meta = &v
}

func (o BuildsWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildsWithoutIncludesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableBuildsWithoutIncludesResponse struct {
	value *BuildsWithoutIncludesResponse
	isSet bool
}

func (v NullableBuildsWithoutIncludesResponse) Get() *BuildsWithoutIncludesResponse {
	return v.value
}

func (v *NullableBuildsWithoutIncludesResponse) Set(val *BuildsWithoutIncludesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildsWithoutIncludesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildsWithoutIncludesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildsWithoutIncludesResponse(val *BuildsWithoutIncludesResponse) *NullableBuildsWithoutIncludesResponse {
	return &NullableBuildsWithoutIncludesResponse{value: val, isSet: true}
}

func (v NullableBuildsWithoutIncludesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildsWithoutIncludesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
