/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardImageCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardImageCreateRequestData{}

// GameCenterLeaderboardImageCreateRequestData struct for GameCenterLeaderboardImageCreateRequestData
type GameCenterLeaderboardImageCreateRequestData struct {
	Type          string                                                    `json:"type"`
	Attributes    AppClipAdvancedExperienceImageCreateRequestDataAttributes `json:"attributes"`
	Relationships GameCenterLeaderboardImageCreateRequestDataRelationships  `json:"relationships"`
}

// NewGameCenterLeaderboardImageCreateRequestData instantiates a new GameCenterLeaderboardImageCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardImageCreateRequestData(type_ string, attributes AppClipAdvancedExperienceImageCreateRequestDataAttributes, relationships GameCenterLeaderboardImageCreateRequestDataRelationships) *GameCenterLeaderboardImageCreateRequestData {
	this := GameCenterLeaderboardImageCreateRequestData{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewGameCenterLeaderboardImageCreateRequestDataWithDefaults instantiates a new GameCenterLeaderboardImageCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardImageCreateRequestDataWithDefaults() *GameCenterLeaderboardImageCreateRequestData {
	this := GameCenterLeaderboardImageCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterLeaderboardImageCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardImageCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterLeaderboardImageCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GameCenterLeaderboardImageCreateRequestData) GetAttributes() AppClipAdvancedExperienceImageCreateRequestDataAttributes {
	if o == nil {
		var ret AppClipAdvancedExperienceImageCreateRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardImageCreateRequestData) GetAttributesOk() (*AppClipAdvancedExperienceImageCreateRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GameCenterLeaderboardImageCreateRequestData) SetAttributes(v AppClipAdvancedExperienceImageCreateRequestDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *GameCenterLeaderboardImageCreateRequestData) GetRelationships() GameCenterLeaderboardImageCreateRequestDataRelationships {
	if o == nil {
		var ret GameCenterLeaderboardImageCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardImageCreateRequestData) GetRelationshipsOk() (*GameCenterLeaderboardImageCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *GameCenterLeaderboardImageCreateRequestData) SetRelationships(v GameCenterLeaderboardImageCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o GameCenterLeaderboardImageCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardImageCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

type NullableGameCenterLeaderboardImageCreateRequestData struct {
	value *GameCenterLeaderboardImageCreateRequestData
	isSet bool
}

func (v NullableGameCenterLeaderboardImageCreateRequestData) Get() *GameCenterLeaderboardImageCreateRequestData {
	return v.value
}

func (v *NullableGameCenterLeaderboardImageCreateRequestData) Set(val *GameCenterLeaderboardImageCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardImageCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardImageCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardImageCreateRequestData(val *GameCenterLeaderboardImageCreateRequestData) *NullableGameCenterLeaderboardImageCreateRequestData {
	return &NullableGameCenterLeaderboardImageCreateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardImageCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardImageCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
