/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard{}

// GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard struct for GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard
type GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard struct {
	Data *GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner `json:"data,omitempty"`
}

// NewGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard instantiates a new GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard() *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard {
	this := GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard{}
	return &this
}

// NewGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboardWithDefaults instantiates a new GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboardWithDefaults() *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard {
	this := GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) GetData() GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner {
	if o == nil || IsNil(o.Data) {
		var ret GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) GetDataOk() (*GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner and assigns it to the Data field.
func (o *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) SetData(v GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner) {
	o.Data = &v
}

func (o GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard struct {
	value *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard
	isSet bool
}

func (v NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) Get() *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard {
	return v.value
}

func (v *NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) Set(val *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard(val *GameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) *NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard {
	return &NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard{value: val, isSet: true}
}

func (v NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterDetailUpdateRequestDataRelationshipsDefaultLeaderboard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
