/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAchievementRelationshipsGameCenterGroupData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAchievementRelationshipsGameCenterGroupData{}

// GameCenterAchievementRelationshipsGameCenterGroupData struct for GameCenterAchievementRelationshipsGameCenterGroupData
type GameCenterAchievementRelationshipsGameCenterGroupData struct {
	Type string `json:"type"`
	Id   string `json:"id"`
}

// NewGameCenterAchievementRelationshipsGameCenterGroupData instantiates a new GameCenterAchievementRelationshipsGameCenterGroupData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAchievementRelationshipsGameCenterGroupData(type_ string, id string) *GameCenterAchievementRelationshipsGameCenterGroupData {
	this := GameCenterAchievementRelationshipsGameCenterGroupData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewGameCenterAchievementRelationshipsGameCenterGroupDataWithDefaults instantiates a new GameCenterAchievementRelationshipsGameCenterGroupData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAchievementRelationshipsGameCenterGroupDataWithDefaults() *GameCenterAchievementRelationshipsGameCenterGroupData {
	this := GameCenterAchievementRelationshipsGameCenterGroupData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GameCenterAchievementRelationshipsGameCenterGroupData) SetId(v string) {
	o.Id = v
}

func (o GameCenterAchievementRelationshipsGameCenterGroupData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAchievementRelationshipsGameCenterGroupData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGameCenterAchievementRelationshipsGameCenterGroupData struct {
	value *GameCenterAchievementRelationshipsGameCenterGroupData
	isSet bool
}

func (v NullableGameCenterAchievementRelationshipsGameCenterGroupData) Get() *GameCenterAchievementRelationshipsGameCenterGroupData {
	return v.value
}

func (v *NullableGameCenterAchievementRelationshipsGameCenterGroupData) Set(val *GameCenterAchievementRelationshipsGameCenterGroupData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAchievementRelationshipsGameCenterGroupData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAchievementRelationshipsGameCenterGroupData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAchievementRelationshipsGameCenterGroupData(val *GameCenterAchievementRelationshipsGameCenterGroupData) *NullableGameCenterAchievementRelationshipsGameCenterGroupData {
	return &NullableGameCenterAchievementRelationshipsGameCenterGroupData{value: val, isSet: true}
}

func (v NullableGameCenterAchievementRelationshipsGameCenterGroupData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAchievementRelationshipsGameCenterGroupData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
