/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterLeaderboardUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardUpdateRequest{}

// GameCenterLeaderboardUpdateRequest struct for GameCenterLeaderboardUpdateRequest
type GameCenterLeaderboardUpdateRequest struct {
	Data GameCenterLeaderboardUpdateRequestData `json:"data"`
}

// NewGameCenterLeaderboardUpdateRequest instantiates a new GameCenterLeaderboardUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardUpdateRequest(data GameCenterLeaderboardUpdateRequestData) *GameCenterLeaderboardUpdateRequest {
	this := GameCenterLeaderboardUpdateRequest{}
	this.Data = data
	return &this
}

// NewGameCenterLeaderboardUpdateRequestWithDefaults instantiates a new GameCenterLeaderboardUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardUpdateRequestWithDefaults() *GameCenterLeaderboardUpdateRequest {
	this := GameCenterLeaderboardUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterLeaderboardUpdateRequest) GetData() GameCenterLeaderboardUpdateRequestData {
	if o == nil {
		var ret GameCenterLeaderboardUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardUpdateRequest) GetDataOk() (*GameCenterLeaderboardUpdateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterLeaderboardUpdateRequest) SetData(v GameCenterLeaderboardUpdateRequestData) {
	o.Data = v
}

func (o GameCenterLeaderboardUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableGameCenterLeaderboardUpdateRequest struct {
	value *GameCenterLeaderboardUpdateRequest
	isSet bool
}

func (v NullableGameCenterLeaderboardUpdateRequest) Get() *GameCenterLeaderboardUpdateRequest {
	return v.value
}

func (v *NullableGameCenterLeaderboardUpdateRequest) Set(val *GameCenterLeaderboardUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardUpdateRequest(val *GameCenterLeaderboardUpdateRequest) *NullableGameCenterLeaderboardUpdateRequest {
	return &NullableGameCenterLeaderboardUpdateRequest{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
