/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect

import (
	"encoding/json"
)

// checks if the GameCenterAchievementImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterAchievementImageResponse{}

// GameCenterAchievementImageResponse struct for GameCenterAchievementImageResponse
type GameCenterAchievementImageResponse struct {
	Data     GameCenterAchievementImage          `json:"data"`
	Included []GameCenterAchievementLocalization `json:"included,omitempty"`
	Links    DocumentLinks                       `json:"links"`
}

// NewGameCenterAchievementImageResponse instantiates a new GameCenterAchievementImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterAchievementImageResponse(data GameCenterAchievementImage, links DocumentLinks) *GameCenterAchievementImageResponse {
	this := GameCenterAchievementImageResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewGameCenterAchievementImageResponseWithDefaults instantiates a new GameCenterAchievementImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterAchievementImageResponseWithDefaults() *GameCenterAchievementImageResponse {
	this := GameCenterAchievementImageResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GameCenterAchievementImageResponse) GetData() GameCenterAchievementImage {
	if o == nil {
		var ret GameCenterAchievementImage
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementImageResponse) GetDataOk() (*GameCenterAchievementImage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GameCenterAchievementImageResponse) SetData(v GameCenterAchievementImage) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *GameCenterAchievementImageResponse) GetIncluded() []GameCenterAchievementLocalization {
	if o == nil || IsNil(o.Included) {
		var ret []GameCenterAchievementLocalization
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementImageResponse) GetIncludedOk() ([]GameCenterAchievementLocalization, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *GameCenterAchievementImageResponse) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []GameCenterAchievementLocalization and assigns it to the Included field.
func (o *GameCenterAchievementImageResponse) SetIncluded(v []GameCenterAchievementLocalization) {
	o.Included = v
}

// GetLinks returns the Links field value
func (o *GameCenterAchievementImageResponse) GetLinks() DocumentLinks {
	if o == nil {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GameCenterAchievementImageResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GameCenterAchievementImageResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o GameCenterAchievementImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterAchievementImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

type NullableGameCenterAchievementImageResponse struct {
	value *GameCenterAchievementImageResponse
	isSet bool
}

func (v NullableGameCenterAchievementImageResponse) Get() *GameCenterAchievementImageResponse {
	return v.value
}

func (v *NullableGameCenterAchievementImageResponse) Set(val *GameCenterAchievementImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterAchievementImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterAchievementImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterAchievementImageResponse(val *GameCenterAchievementImageResponse) *NullableGameCenterAchievementImageResponse {
	return &NullableGameCenterAchievementImageResponse{value: val, isSet: true}
}

func (v NullableGameCenterAchievementImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterAchievementImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
